'many' can count number of failures

diff --git a/many b/many
--- a/many
+++ b/many
@@ -5,6 +5,7 @@ function usage() {
     echo " e.g.: $0 -n 5 -- mvn clean test"
 }
 
+count=false
 finished=''
 times=1
 while [[ $# > 1 ]] && [[ -z $finished ]]
@@ -18,6 +19,9 @@ do
         -n)
             times="$2"
             ;;
+        -c)
+            count=true
+            ;;
     esac
     shift # past argument or value
 done
@@ -28,8 +32,9 @@ if [[ -z "$@" ]] || [[ -z "$finished" ]] ; then
 fi
 
 # run the command however many times it was requested
-command="$@"
+function fail_first() {
 i=0
+command="$@"
 while [[ $i -lt $times ]] ; do
     i=$((i + 1))
     sh -x -c "$command"
@@ -39,3 +44,25 @@ while [[ $i -lt $times ]] ; do
         exit $result
     fi
 done
+}
+function count_failures() {
+i=0
+num_failures=0
+command="$@"
+while [[ $i -lt $times ]] ; do
+    i=$((i + 1))
+    sh -x -c "$command"
+    result=$?
+    if [ $result != 0 ] ; then
+        num_failures=$((num_failures + 1))
+    fi
+done
+echo "Number of failures of total: $num_failures of $times"
+}
+
+if [[ "$count" == true ]] ; then
+    echo "Counting failures"
+    count_failures "$@"
+else
+    fail_first "$@"
+fi
